### ISSUE TITLE
关于换行符自动监测

### ISSUE THREAD

**Issue by chiperman** [daibor/nonsense.fun#10]
目前换行都需要写`<br>`，还是比较不方便的，本来想自己写一个检测脚本，类似网址现在的**识别 URL 链接**。
可是我看了一下目前直接按回车后，网页代码中并没有任何显示
![image](https://user-images.githubusercontent.com/34889778/90974164-2ee89300-e55b-11ea-958d-5c5db0dad633.png)
![image](https://user-images.githubusercontent.com/34889778/90974173-3c9e1880-e55b-11ea-9819-16e4092ec788.png)
请问有什么思路吗？

**Comment by daibor** [comment]
在内容对应的 css 属性里加这个试试
white-space:pre;
我记得之前有 mr 已经合进来了，你看看～

**Comment by chiperman** [comment]
谢谢，已经解决。请问有计划添加图片么？

**Comment by Yifeng-J** [comment]
@chiperman  请问你下面的#标签是如何设置的

**Comment by chiperman** [comment]
@Yifeng-J 直接写了一个 HTML 的标签，然后在进行 HTTP 请求的时候，增加一个 content 存放 #标签 的数据，然后用渲染正文的方式渲染标签。格式如下：
 ```<tag id="tag" v-html='item.attributes.tag'></tag>```

**Comment by Yifeng-J** [comment]
@chiperman 感谢
